
extern NSString* const TEST_BANNER_ADUNIT_ID;
extern NSString* const TEST_INTERSTITIAL_ADUNIT_ID;
extern NSString* const TEST_REWARDED_ADUNIT_ID;
extern NSString* const TEST_NATIVE_ADVANCED_ADUNIT_ID;

extern NSString* const INFOPLIST_KEY_ADMOB_BANNER_ID;
extern NSString* const INFOPLIST_KEY_ADMOB_INTERSTITIAL_ID;
extern NSString* const INFOPLIST_KEY_ADMOB_REWARDED_ID;
extern NSString* const INFOPLIST_KEY_ADMOB_NATIVE_ADVANCED_ID;
